# Generated by Django 5.0.6 on 2024-08-25 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_cartitems_cart_products_delete_cartitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cart_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.cart",
            ),
        ),
    ]
