# Generated by Django 5.0.6 on 2024-08-25 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_order_cart_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="cart_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventory.cart"
            ),
        ),
    ]
