# Generated by Django 5.0.6 on 2024-08-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_alter_order_cart_id"),
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="products",
            field=models.ManyToManyField(
                related_name="cartItems",
                through="inventory.CartItems",
                to="shop.product",
            ),
        ),
    ]
