# Generated by Django 5.0.6 on 2024-08-26 08:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0006_orderitems"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="products",
        ),
    ]
