# Generated by Django 5.0.6 on 2024-08-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0007_remove_order_products"),
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(
                related_name="orderItems",
                through="inventory.OrderItems",
                to="shop.product",
            ),
        ),
    ]
